Rewrote deepshell

diff --git a/src/deepshell b/src/deepshell
--- a/src/deepshell
+++ b/src/deepshell
@@ -16,64 +16,74 @@
 # GNU General Public License for more details.
 #
 # You should have received a copy of the GNU General Public License
-# along with this software; see the file COPYING.  If not, write to
-# the Free Software Foundation, Inc., 59 Temple Place, Suite 330,
-# Boston, MA 02111-1307 USA
+# along with this software; see the file COPYING.  If not, see
+# <http://www.gnu.org/licenses/>.
 
-### DSWM Testing Tool.
+### DeepShell - DSWM Interactive SHell.
 
 #### INIT ####
-if sleep --version 2>/dev/null | grep -q GNU
+DELAY=0.01
+
+if ! sleep $DELAY 2>/dev/null >&2
 then
-    DELAY=0.1
-else
     DELAY=1
 fi
 
-#### /INIT ####
+# replace -E with -r option for old versions of GNU sed
+if ! sed -E 1p /dev/null 2>/dev/null; then
+    sed() { shift; command sed -r "$@"; }
+fi
+
+# parse C-style backslash sequences by default
+if [ "$(echo -e foo)" = foo ]; then
+    echo() { builtin echo -e "$@"; }
+fi
 
 function wait_result ()
 {
     while :; do
-	RESULT=`xprop -display $DISPLAY -root -f DSWM_COMMAND_RESULT 8s DSWM_COMMAND_RESULT 2>/dev/null`
-	
-	if echo "$RESULT" | grep -v -q 'not found.$'; then
-	    if ! echo "$RESULT" | grep -q '= $'; then
-		echo ""
-		echo -n " } Execution INFO: "
-		echo $RESULT | sed 's/[^"]*"//;s/"$//;s/\\n/\n/g;s/\\"/"/g;s/\n\+$//;
-	    		s/\^[*[:digit:]]\{2\}//g;s/\^[Bbn]//g;'
-		echo -n " } "
-	    fi
-	    return 1
+	RESULT=$(xprop -root -f DSWM_COMMAND_RESULT 8s \
+	    DSWM_COMMAND_RESULT 2>/dev/null |
+	    sed -E 's/\\([[:digit:]]+)/\\0\1/g')
+	if echo "$RESULT" | grep -v -q 'not found.$'
+	then
+	    break
 	fi
+	
 	sleep $DELAY
     done
-
-    xprop -display $DISPLAY -root -remove DSWM_COMMAND_RESULT
-
-    if [ ! -z "$(echo "$RESULT" | grep -q '= $')" ]; then
-    	return 1
+    
+    xprop -root -remove DSWM_COMMAND_RESULT
+    
+    if echo "$RESULT" | grep -q '= $'
+    then
+	return 1
     fi
-
-    echo $RESULT | sed 's/[^"]*"//;s/"$//;s/\\n/\n/g;s/\\"/"/g;s/\n\+$//;
-			s/\^[*[:digit:]]\{2\}//g;s/\^[Bbn]//g;'
+    
+    echo "$RESULT" |
+    sed -E 's/[^"\\n]+"//
+            /^"[[:space:]]*$/d
+            s/(^|[^\\])\\n/\1\
+/g
+            s/\\(["\\n])/\1/g
+            s/\^([*[:digit:]]+|[Bbn])//g'
 }
 
 function send_cmd ()
 {
     local cmd="$1"
     
-    if [ "$cmd" = "dswm-quit" ]; then
+    if [ "$cmd" = "dswm-quit" ]
+    then
 	cmd=quit
-    elif [ "$cmd" = "quit" ]; then
-	exit 0
+    elif [ "$cmd" = "quit" ]
+    then
+	exit
     fi
     
-    xprop -display $DISPLAY -root -f DSWM_COMMAND 8s -set DSWM_COMMAND "$cmd"
+    xprop -root -f DSWM_COMMAND 8s -set DSWM_COMMAND "$cmd"
     
     wait_result
-
 }
 
 function usage ()
@@ -115,10 +125,29 @@ EXAMPLES:
        echo '(group-windows (current-group))' | $0 eval  # eval some code on DSWM
        $0 -e <enter dswm commands with arguments> Ctrl+D # exec all given DSWM commands
 EOF
-
-exit 0
-
+    exit 0;
 }
+
+function warn ()
+{
+  {
+    tput md bold
+    tput AF setaf 1
+    echo 'WARN:\c'
+    tput me sgr0
+    echo " $*"
+  } >&2
+}
+
+function tput ()
+{
+    local cap1=$1 cap2=$2
+    shift 2
+
+    command tput $cap1 $@ 2>/dev/null ||
+    command tput $cap2 $@ 2>/dev/null
+}
+
 
 function do_commands ()
 {
@@ -127,7 +156,7 @@ function do_commands ()
 	    break
 	else
 	    echo -n ">> Doing $i... "
-	    		
+	    
 	    send_cmd $(echo $i | sed 's/\_/\ /g')
 	    
 	    if [ "$DEBUG" == "1" ]; then
@@ -136,7 +165,7 @@ function do_commands ()
 	    fi
 	    
 	    if [ $? == 0 ]; then
-		echo "done"
+		echo "[ done ]"
 	    else
 		echo "Failed!"
 	    fi
@@ -147,35 +176,80 @@ function do_commands ()
 
 function dswm_shell ()
 {
-    if type rlwrap >/dev/null 2>&1; then
+
+    if ! type rlwrap 2>/dev/null >&2; then
+	warn rlwrap not found, command completion won\'t work
+    else
 	    # Note: $TEMP is not conventional; it is left here purely
 	    # for backwards compatibility.
-	COMMANDS="${TEMP:-${TEMPDIR:-/var/tmp}}/dttool.commands.$$"
-	echo `do_commands "commands"` | sed 's/[[:space:]]\+/\n/g' | sort > "$COMMANDS"
-	rlwrap -f "$COMMANDS" "$0" -r
-	rm -f "$COMMANDS"
-	exit
+ 	COMMANDS="${TEMP:-${TMPDIR:-/tmp:-/var/tmp}}/deepshell.commands.$$"
+	echo `do_commands "commands"` | ## sort > "$COMMANDS"
+ 	sed -E 's/[[:space:]]+/\
+/g' |
+ 	sort > "$COMMANDS"
+ 	trap 'rm -f "$COMMANDS"' exit int term
+ 	rlwrap -b '' -f "$COMMANDS" "$0" -r
+ 	exit
     fi
-    
-    tput setaf 5
-    echo Welcome to the DSWM Testing Tool\`s interactive shell.
-    tput sgr0
-    echo -n 'Type '
-    tput setaf 2
-    echo -n commands
-    tput sgr0
+
+    tput AF setaf 5
+    echo Welcome to the DeepShell - DSWM Interactive SHell.
+    tput me sgr0
+    echo 'Type \c'
+    tput AF setaf 2
+    echo 'commands\c'
+    tput me sgr0
     echo \ for a list of commands.
     
     IFS='
 '
-    echo -n "> "
-    while read REPLY; do
-	tput bold
-	tput setaf 2
+    while read -p '> ' REPLY; do
+	tput md bold
+	tput AF setaf 2
 	do_commands "$REPLY"
-	tput sgr0
-	echo -n "> "
+	tput me sgr0
     done
+
+# 	if ! type rlwrap 2>/dev/null >&2
+# 	then
+# 	    warn rlwrap not found, command completion won\'t work
+# 	elif [ $READLINE = yes ]
+# 	then
+# 	    COMMANDS="${TMPDIR:-/tmp}/dsish.commands.$$"
+# 	    echo $(send_cmd "commands") |
+# 	    sed -E 's/[[:space:]]+/\
+# /g' |
+# 	    sort > "$COMMANDS"
+# 	    trap 'rm -f "$COMMANDS"' exit int term
+# 	    rlwrap -b '' -f "$COMMANDS" "$0" -r
+# 	    exit
+# 	fi
+
+# 	tput AF setaf 5
+#         echo Welcome to the DSWM Interactive SHell.
+#         tput me sgr0
+#         echo 'Type \c'
+#         tput AF setaf 2
+#         echo 'commands\c'
+#         tput me sgr0
+#         echo \ for a list of commands.
+
+# 	while read -p '> ' REPLY
+# 	do
+# 	    tput md bold
+# 	    tput AF setaf 2
+# 	    send_cmd "$REPLY"
+# 	    tput me sgr0
+# 	done
+#     else
+# 	while read REPLY
+# 	do
+# 	    send_cmd "$REPLY"
+# 	done
+#     fi
+# fi
+
+
 }
 
 ############### /deepshell part ##############
